### ISSUE TITLE
quick and dirty url extraction

### ISSUE THREAD

**Issue by jxu** [jstrieb/panopto-download#3]
If all the python script does is parse the RSS XML to find mp4 links, then something like `grep mp4 Podcast.xml` is enough to get some links. Maybe extract URLs with `xq`

**Comment by jstrieb** [comment]
This is true. Originally, I had intended to add a parallel downloading feature, but haven't gotten around to it. I would likely implement it using `aiohttp`.

Note that in general (particularly since addressing #4), the key difference is that this program can also parse out the correct title for a given video, so that the filename can reflect the video contents. This program is also easily extensible, and I have imported this Python script into other, larger scripts that I run as part of a `cron`-scheduled pipeline to back up course materials. 

Though your comment is certainly correct, in the meantime, I will close this issue. Thanks for taking a look at the project!

**Comment by jxu** [comment]
I have been messing around with xq. For only the links: 

    xq '//item/enclosure/@url' Podcast.ashx | sed '1d;$d;s/^  //g;s/<[^>]*>//g' | wget -i -

The sed statement is only to process the output of xq (excuse my possibly poor use of sed - in the spirit of quick and dirty, the sed command just cleans up the XML output of xq). If xq had a raw output option (https://github.com/jeffbr13/xq/issues/5) it would be unnecessary. 

For titles also, we also find title or podcast url, printing as we go then adding .mp4, but use null terminated items rather than quotes for titles with spaces.

    xq '//item/enclosure/@url | //item/title/text()' Podcast.ashx | sed '1d;$d;s/^  //g;s/<[^>]*>//g' | sed '1~2s/$/\.mp4/' | tr \\n \\0 | xargs -0 -L 2 wget -O

btw `wget -c` can be used to not redownload existing files.

Posted here https://gist.github.com/jxu/f4730d66fb491805e0932c864e0a9807

**Comment by jxu** [comment]
I'm not sure when it was really added, but youtube-dl and yt-dlp generic extractor on the podcast url seems to be able to get the correct title just by searching for title tags in XML https://github.com/yt-dlp/yt-dlp/commit/76c73715fb1e0eee61ace5ff7855d8237abdcd54
