### ISSUE TITLE
Direct link - xml.etree.ElementTree.ParseError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by hejops** [jstrieb/panopto-download#4]
My institution does not support RSS feeds, so I tried to use the direct link to a video and got the following error:

```
$ python3 panopto-video-urls.py https://...panopto.eu/Panopto/Pages/Viewer.aspx?id=dcd84143-6e33-4922-8b4a-ac8301593910
Traceback (most recent call last):
  File "panopto-video-urls.py", line 87, in <module>
    main()
  File "panopto-video-urls.py", line 67, in main
    video_urls, video_titles = parse_xml(podcast_url)
  File "panopto-video-urls.py", line 42, in parse_xml
    root = ET.fromstring(data)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 69, column 53

Page source:
allowVideoPodcastFeeds: false,
allowAudioPodcastFeeds: false,
```

Are direct links supported?

**Comment by jstrieb** [comment]
At the moment, the program does not support direct links. However, I believe it would be fairly easy to add this feature.

The caveat is that the program will only be able to download from a direct link if it is possible to view the particular Panopto `Viewer.aspx` page without logging in or authenticating. A manual way to check whether logging in is required to view a page is to open the direct link in an incognito or private window. If it opens without prompting you to log in, the downloader will be able to fetch it; otherwise, it will not. Downloading videos that require authentication would necessitate loading in each user's cookies, which is possible, but which I don't have time to implement at the moment. 

The feature I add will pull the direct link and look for an HTML `meta` tag with the attribute: `property="og:video"`. This tag seems to be present in all of the example viewer pages I have seen, and contains the mp4 URL to be downloaded. It is possible to manually download a video without using this program by doing "View Source" in the browser and using this tag.

Shortly, I will push an update that addresses this issue.

**Comment by jstrieb** [comment]
This commit should fix your issue. If not, please let me know. I will close this issue in a few days if there are no reported problems.

Thanks for using the project!

**Comment by hejops** [comment]
Seems like login is also required for my institution. Oh well. Appreciate the work you've done!

**Comment by jstrieb** [comment]
Even though my program for batch downloading probably won't work, it is still possible to download the video if you right click and "View Source" on the page, and search for `og:video`. You should then be able to go to the URL in the `property` attribute of that tag, and save the video from there.

Best of luck!

**Comment by jxu** [comment]
This slightly defeats the point of using the utility which is for bulk downloading. There was a PR for youtube-dl to support individual panopto videos but I don't think it was ever merged.

**Comment by jstrieb** [comment]
Reopening this issue, since I plan to add this functionality by the end of the semester. It will probably involve pasting in a session cookie as a command-line argument, or something like that.

**Comment by jstrieb** [comment]
Just pushed a commit that should fix this. Added a command-line option for an `.ASPXAUTH` session cookie that will allow downloading from Panopto instances behind login pages.
